### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by squishan** [fcbarbi/ardl#1]
when running `devtools::install_github("fcbarbi/ardl")` I encountered the following error message

> Downloading GitHub repo fcbarbi/ardl@master
> from URL https://api.github.com/repos/fcbarbi/ardl/zipball/master
> Installing ardl
> "C:/Users/squirsa/AppData/Local/R/R-33~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
>   "C:/Users/squirsa/AppData/Local/Temp/RtmpoxuGW4/devtools1e3057c4771f/fcbarbi-ardl-d53229e" --library="\USDALHOME01/squirsa/My Documents/R/win-library/3.3"  \
>   --install-tests 
- installing _source_ package 'ardl' ...
  *\* R
  *\* data
  *\* inst
  Warning in file.create(to[okay]) :
  cannot create file '\USDALHOME01/squirsa/My Documents/R/win-library/3.3/ardl/CITATION', reason 'No such file or directory'
  *\* preparing package for lazy loading
  *\* help
  **\* installing help indices
  *\* building package indices
  *\* installing vignettes
  *\* testing if installed package can be loaded
  **\* arch - i386
  Warning in library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE) :
  no library trees found in 'lib.loc'
  Error: loading failed
  Execution halted
  **\* arch - x64
  Warning in library(pkg_name, lib.loc = lib, character.only = TRUE, logical.return = TRUE) :
  no library trees found in 'lib.loc'
  Error: loading failed
  Execution halted
  ERROR: loading failed for 'i386', 'x64'
- removing '\USDALHOME01/squirsa/My Documents/R/win-library/3.3/ardl'
  Error: Command failed (1)

**Comment by fcbarbi** [comment]
It seems that Windows can't find a directory so you could try a manual install:

1. Download from `https://github.com/fcbarbi/ardl` the file `ardl-master.zip` and save in a known directory like `D:\temp`.
2. Unzip it and rename the directory from `ardl-master` to `ardl` so now you have all the package files in the directory `D:\temp\ardl`.
3. From inside R run the command 
`install.packages("D:/temp/ardl",repos=NULL, type="source")`
Alternatively, you can do 
`install.packages("D:\\temp\\ardl",repos=NULL, type="source")`

**Comment by gonlairo** [comment]
I have the same problem. When I try to install it manually, it gives me the following error:

Installing package into ‘C:/Users/Rodrigo González/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
* installing *source* package 'ardl' ...
Warning in file(file, if (append) "a" else "w") :
  cannot open file 'C:/Users/Rodrigo Gonzalez/Documents/R/win-library/3.4/ardl/DESCRIPTION': No such file or directory
Error in file(file, if (append) "a" else "w") : 
  no se puede abrir la conexión
ERROR: installing package DESCRIPTION failed for package 'ardl'
* removing 'C:/Users/Rodrigo González/Documents/R/win-library/3.4/ardl'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\Rodrigo González\Documents\R\win-library\3.4" "C:/Users/RODRIG~1/DOCUME~1/ardl"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/RODRIG~1/DOCUME~1/ardl’ had non-zero exit status

If you could help me, I´d be grateful.

**Comment by fcbarbi** [comment]
Hello Rodrigo, Thank you for your feedback. 
It looks like it's an access rights problem as it says that it can't write the file 'C:/Users/Rodrigo Gonzalez/Documents/R/win-library/3.4/ardl/DESCRIPTION'. Do you have write access to the directory "C:/Users/Rodrigo González/Documents/R/win-library/3.4" ? You can try to create a simple text file in this directory to check that your user has the rights to do so. Please do something like: 
1.cd C:/Users/Rodrigo González/Documents/R/win-library/3.4, 2.mkdir ardl, 3.cd ardl, 4.dir > test.txt. I can only test on Windows on Monday. Fernando

**Comment by gonlairo** [comment]
I did what you asked and it created the text file correctly so I don´t really know what is happening.

It would be great if you could test that. I will be waiting for your answer.

Thank you.
